Update 05-otrs

diff --git a/6/install/etc/cont-init.d/05-otrs b/6/install/etc/cont-init.d/05-otrs
--- a/6/install/etc/cont-init.d/05-otrs
+++ b/6/install/etc/cont-init.d/05-otrs
@@ -30,7 +30,7 @@ function set_logo () {
 \n    'StyleRight' => '${logo_right}px',\
 \n    'StyleTop' => '${logo_top}px',\
 \n    'StyleWidth' => '${logo_width}px',\
-\n    'URL' => '$logo_url'\n};" /var/lib/otrs/Kernel/Config.pm
+\n    'URL' => '$logo_url'\n};" /opt/otrs/Kernel/Config.pm
 }
 
 
@@ -80,23 +80,23 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
       echo "** [otrs] Starting a clean OTRS installation ready to be configured !!"
 
 #### Setup Data Persistence
-    if [ ! -f /var/lib/otrs/Kernel/Config.pm ]; then
+    if [ ! -f /opt/otrs/Kernel/Config.pm ]; then
         echo "** [otrs] Found empty configuration directory, copying default configuration to it"
-        mkdir -p /var/lib/otrs/Kernel
-        cp -R /assets/otrs-config/* /var/lib/otrs/
+        mkdir -p /opt/otrs/Kernel
+        cp -R /assets/otrs-config/* /opt/otrs/
         if [ $? -eq 0 ];
           then
             :
           else
-            echo "** [otrs] ERROR: Can't move OTRS configuration directory to /var/lib/otrs/Kernel" && exit 1
+            echo "** [otrs] ERROR: Can't move OTRS configuration directory to /opt/otrs/Kernel" && exit 1
         fi
     fi
 
 #### Configure DB
-    sed  -i "s/\($Self->{'DatabaseHost'} *= *\).*/\1'$DB_HOST';/" /var/lib/otrs/Kernel/Config.pm
-    sed  -i "s/\($Self->{'Database'} *= *\).*/\1'$DB_NAME';/" /var/lib/otrs/Kernel/Config.pm
-    sed  -i "s/\($Self->{'Database'} *= *\).*/\1'$DB_USER';/" /var/lib/otrs/Kernel/Config.pm
-    sed  -i "s/\($Self->{'DatabasePw'} *= *\).*/\1'$DB_PASS';/" /var/lib/otrs/Kernel/Config.pm
+    sed  -i "s/\($Self->{'DatabaseHost'} *= *\).*/\1'$DB_HOST';/" /opt/otrs/Kernel/Config.pm
+    sed  -i "s/\($Self->{'Database'} *= *\).*/\1'$DB_NAME';/" /opt/otrs/Kernel/Config.pm
+    sed  -i "s/\($Self->{'Database'} *= *\).*/\1'$DB_USER';/" /opt/otrs/Kernel/Config.pm
+    sed  -i "s/\($Self->{'DatabasePw'} *= *\).*/\1'$DB_PASS';/" /opt/otrs/Kernel/Config.pm
 
 #### Add default config options
     sed -i "/$Self->{'SecureMode'} = 1;/a \
@@ -106,16 +106,16 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
   \n\    \$Self->{'CustomerHeadline'} = '$ORGANIZATION';\
   \n\    \$Self->{'SystemID'} = '$SYSTEM_ID';\
   \n\    \$Self->{'PostMaster::PreFilterModule::NewTicketReject::Sender'} = 'noreply@${HOSTNAME}';"\
-   /var/lib/otrs/Kernel/Config.pm
+   /opt/otrs/Kernel/Config.pm
 
 #### Populate Database
         echo "** [otrs] Loading default db schema..."
-        $mysqlcmd $DB_NAME < /var/lib/otrs/scripts/database/otrs-schema.mysql.sql
+        $mysqlcmd $DB_NAME < /opt/otrs/scripts/database/otrs-schema.mysql.sql
         [ $? -gt 0 ] && echo "ERROR: Couldn't load OTRS database schema !!" && exit 1
         echo "** [otrs] Loading initial db inserts..."
-        $mysqlcmd $DB_NAME < /var/lib/otrs/scripts/database/otrs-initial_insert.mysql.sql
+        $mysqlcmd $DB_NAME < /opt/otrs/scripts/database/otrs-initial_insert.mysql.sql
         [ $? -gt 0 ] && echo "ERROR: Couldn't load OTRS database initial inserts !!" && exit 1
-        $mysqlcmd $DB_NAME < /var/lib/otrs/scripts/database/otrs-schema-post.mysql.sql
+        $mysqlcmd $DB_NAME < /opt/otrs/scripts/database/otrs-schema-post.mysql.sql
         [ $? -gt 0 ] && echo "ERROR: Couldn't load OTRS database schema post inserts !!" && exit 1
     else
       echo "** [otrs] Existing OTRS Installation found..."
@@ -124,7 +124,7 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
 
   
 ### Set Skins
-  [ ! -z $AGENT_SKIN ] &&  sed -i "/$Self->{'SecureMode'} = 1;/a \$Self->{'Loader::Agent::DefaultSelectedSkin'} =  '$AGENT_SKIN';\n\$Self->{'Loader::Customer::SelectedSkin'} =  '$CUSTOMER_SKIN';" /var/lib/otrs/Kernel/Config.pm
+  [ ! -z $AGENT_SKIN ] &&  sed -i "/$Self->{'SecureMode'} = 1;/a \$Self->{'Loader::Agent::DefaultSelectedSkin'} =  '$AGENT_SKIN';\n\$Self->{'Loader::Customer::SelectedSkin'} =  '$CUSTOMER_SKIN';" /opt/otrs/Kernel/Config.pm
 
 ### Set Logos
   [ ! -z $AGENT_LOGO ] && set_logo "Agent" $AGENT_LOGO_HEIGHT $AGENT_LOGO_RIGHT $AGENT_LOGO_TOP $AGENT_LOGO_WIDTH $AGENT_LOGO
@@ -133,24 +133,24 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
 ### Set Ticket Counter
     if [ ! -z "${TICKET_COUNTER}" ]; then
     echo "** [otrs] Setting the start of the ticket counter to: '$TICKET_COUNTER'"
-    echo "$TICKET_COUNTER" > /var/lib/otrs/var/log/TicketCounter.log
+    echo "$TICKET_COUNTER" > /opt/otrs/var/log/TicketCounter.log
   fi
   if [ ! -z "$NUMBER_GENERATOR" ]; then
     echo "Setting ticket number generator to: '$NUMBER_GENERATOR'"
-    sed -i "/$Self->{'SecureMode'} = 1;/a \$Self->{'Ticket::NumberGenerator'} =  'Kernel::System::Ticket::Number::${NUMBER_GENERATOR}';" /var/lib/otrs/Kernel/Config.pm
+    sed -i "/$Self->{'SecureMode'} = 1;/a \$Self->{'Ticket::NumberGenerator'} =  'Kernel::System::Ticket::Number::${NUMBER_GENERATOR}';" /opt/otrs/Kernel/Config.pm
   fi
 
 ### Set Default Language
   if [ ! -z $LANGUAGE ]; then
     echo "** [otrs] Setting default language to: '$LANGUAGE'"
-    sed -i "/$Self->{'SecureMode'} = 1;/a $Self->{'DefaultLanguage'} = '$LANGUAGE';" /var/lib/otrs/Kernel/Config.pm
+    sed -i "/$Self->{'SecureMode'} = 1;/a $Self->{'DefaultLanguage'} = '$LANGUAGE';" /opt/otrs/Kernel/Config.pm
  fi
   export LANG
 
   
 ### Set Permissions
   echo '** [otrs] Setting Permissions'
-  /var/lib/otrs/bin/otrs.SetPermissions.pl --otrs-user=otrs --web-group=www-data > /dev/null 2>&1
+  /opt/otrs/bin/otrs.SetPermissions.pl --otrs-user=otrs --web-group=www-data > /dev/null 2>&1
   mkdir -p /www/logs/otrs
   chown -R otrs:www-data /www/logs/otrs/
   
@@ -160,7 +160,7 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
       #Disable email fetching
       :
     else
-      echo $FETCH_TIME' * * * * su -s /bin/sh otrs -c /var/lib/otrs/bin/otrs.Postmaster.pl >> /dev/null 2>&1' >> /assets/cron/crontab.txt
+      echo $FETCH_TIME' * * * * su -s /bin/sh otrs -c /opt/otrs/bin/otrs.Postmaster.pl >> /dev/null 2>&1' >> /assets/cron/crontab.txt
   fi
 
 ### Install Addons
@@ -182,19 +182,19 @@ $mysqlcmd -e "use "$DB_NAME"; SELECT * FROM roles;" > /dev/null 2>&1
 
 ### Rebuild Configuration
 echo '** [otrs] Rebuilding Configuration'
-su -s /bin/sh otrs -c "/var/lib/otrs/bin/otrs.Console.pl Maint::Config::Rebuild" > /dev/null 2>&1
+su -s /bin/sh otrs -c "/opt/otrs/bin/otrs.Console.pl Maint::Config::Rebuild" > /dev/null 2>&1
 
 echo '** [otrs] Resetting Cache'
 ### Delete Cache
-su -s /bin/sh otrs -c "/var/lib/otrs/bin/otrs.Console.pl Maint::Cache::Delete" > /dev/null 2>&1
+su -s /bin/sh otrs -c "/opt/otrs/bin/otrs.Console.pl Maint::Cache::Delete" > /dev/null 2>&1
 
 ### Set default admin user password
   echo "** [otrs] Setting password for default admin account root@localhost to: $ROOT_PASS"
-  su -s /bin/sh otrs -c  "/var/lib/otrs/bin/otrs.Console.pl Admin::User::SetPassword root@localhost ${ROOT_PASS}" > /dev/null 2>&1
+  su -s /bin/sh otrs -c  "/opt/otrs/bin/otrs.Console.pl Admin::User::SetPassword root@localhost ${ROOT_PASS}" > /dev/null 2>&1
 
 ### Start OTRS
 echo '** [otrs] Starting OTRS Processes'
-su -s /bin/sh otrs -c '/var/lib/otrs/bin/otrs.Daemon.pl start' > /dev/null 2>&1
+su -s /bin/sh otrs -c '/opt/otrs/bin/otrs.Daemon.pl start' > /dev/null 2>&1
 
 
 mkdir -p /tmp/state/
